apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gitlab-fleet-webhook-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitlab-fleet-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-fleet-leader-election-role
subjects:
- kind: ServiceAccount
  name: gitlab-fleet-controller-manager
  namespace: gitlab-fleet-operator
