apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitlab-fleet-webhook-operator
  name: gitlab-fleet-manager-role
rules:
- apiGroups: ["fleet.cattle.io"]
  resources: ["gitrepos"]
  verbs: ["get", "list", "watch"] # We don't need create permissions
